- name: generate SSH key
  hosts: 127.0.0.1
  connection: local
  vars:
    ansible_user: zyzyx
    ssh_key_filename: id_rsa_myproject
  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"
  tasks:
    - name: generate SSH key "{{ssh_key_filename}}"
      community.crypto.openssh_keypair:
        path: .ssh/{{ssh_key_filename}}
        type: ed25519
        comment: Dstellm@gmail.com