---

- hosts: all
  become: yes
  tasks:
  - name: copy bashrc
    copy:
      src: Files/bashrc
      dest: /home/zyzyx/.bashrc
      owner: zyzyx
      group: zyzyx
      mode: 0740
  - name: copy .zshrc
    copy:
      src: Files/zshrc
      dest: /home/zyzyx/.zshrc
      owner: zyzyx
      group: zyzyx
      mode: 0740
  - name: copy zyzyx.json
    copy:
      src: Files/zyzyx.json
      dest: /home/zyzyx/.poshthemes/zyzyx.omp.json
      owner: zyzyx
      group: zyzyx
      mode: 0740